'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const mobile=matchMedia('(max-width:680px)');
let paused=reduced.matches, scrolling=false,workP=0,lastFrame=-1,scrubOverrideUntil=0;
const header=$('header'),work=$('#work'),track=$('#track'),lab=$('#lab'),heroVideo=$('#hero-video'),scrub=$('#scrub-video'),slider=$('#signal');
function applyMotion(){document.body.classList.toggle('motion-off',paused);document.body.classList.toggle('js-motion',!paused);const b=$('#motion-toggle');b.setAttribute('aria-pressed',String(paused));b.innerHTML=paused?'<span>▷</span> Enable motion':'<span class="pause-icon">Ⅱ</span> Pause motion';if(paused){heroVideo.pause();$$('.ambient-video').forEach(v=>v.pause());}else{heroVideo.play().catch(()=>{});$$('.ambient-video').forEach(v=>{const r=v.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)v.play().catch(()=>{});});}}
applyMotion();$('#motion-toggle').addEventListener('click',()=>{paused=!paused;applyMotion();});reduced.addEventListener('change',()=>{paused=reduced.matches;applyMotion();onScroll();});
const io=new IntersectionObserver(es=>es.forEach(e=>{e.target.classList.toggle('visible',e.isIntersecting)}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
const ambientIO=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target;if(e.isIntersecting&&!paused){v.preload='auto';v.play().catch(()=>{});}else v.pause();}),{threshold:.05});$$('.ambient-video').forEach(v=>ambientIO.observe(v));
const videoIO=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!paused)heroVideo.play().catch(()=>{});else heroVideo.pause()}));videoIO.observe(heroVideo);
let maxTravel=0;
function measure(){maxTravel=Math.max(0,track.scrollWidth-innerWidth);onScroll();}
const clamp=(x,a=0,b=1)=>Math.min(b,Math.max(a,x));
let pendingScrubTime=0;
function flushSeek(){if(Number.isFinite(scrub.duration)&&!scrub.seeking&&Math.abs(scrub.currentTime-pendingScrubTime)>.025)scrub.currentTime=pendingScrubTime;}
function seek(p){const duration=scrub.duration;if(!Number.isFinite(duration))return;pendingScrubTime=clamp(p)*(duration-.05);flushSeek();$('#signal-time').textContent='FRAME '+String(Math.round(p*78)).padStart(3,'0');slider.value=String(Math.round(p*100));}
scrub.addEventListener('seeked',flushSeek);
let scrubLoaded=false;const scrubIO=new IntersectionObserver(es=>{if(es.some(x=>x.isIntersecting)&&!scrubLoaded){scrubLoaded=true;scrub.preload='auto';scrub.load();}},{rootMargin:'400px'});scrubIO.observe(lab);
function onScroll(){if(scrolling)return;scrolling=true;requestAnimationFrame(()=>{scrolling=false;const y=scrollY;const film=$('#film');if(film&&!mobile.matches&&!reduced.matches){const r=film.getBoundingClientRect();film.style.setProperty('--film-progress',clamp(-r.top/(film.offsetHeight-innerHeight)));}header.classList.toggle('scrolled',y>50);const total=document.documentElement.scrollHeight-innerHeight;$('.progress').style.width=(total?y/total*100:0)+'%';if(!mobile.matches&&!reduced.matches){const r=work.getBoundingClientRect();workP=clamp(-r.top/(work.offsetHeight-innerHeight));track.style.transform=`translate3d(${-maxTravel*workP}px,0,0)`;const idx=Math.min(4,Math.round(workP*4));setCounter(idx);}if(!mobile.matches&&!paused&&Date.now()>scrubOverrideUntil){const r=lab.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0)seek(clamp(-r.top/(lab.offsetHeight-innerHeight)));}});}
function setCounter(i){$('#work-counter').textContent=String(i+1).padStart(2,'0')+' / 05';$('.work-line span').style.transform=`translateX(${i*100}%)`;$('#work-prev').disabled=i===0;$('#work-next').disabled=i===4;}
function goWork(dir){if(mobile.matches||reduced.matches){const width=$('.project').offsetWidth+parseFloat(getComputedStyle(track).gap);track.scrollBy({left:dir*width,behavior:paused?'instant':'smooth'});}else{const next=clamp(Math.round(workP*4)+dir,0,4)/4;window.scrollTo({top:work.offsetTop+next*(work.offsetHeight-innerHeight),behavior:paused?'instant':'smooth'});}}
$('#work-prev').addEventListener('click',()=>goWork(-1));$('#work-next').addEventListener('click',()=>goWork(1));track.addEventListener('scroll',()=>{if(mobile.matches||reduced.matches)setCounter(clamp(Math.round(track.scrollLeft/($('.project').offsetWidth+parseFloat(getComputedStyle(track).gap))),0,4))},{passive:true});
track.addEventListener('focusin',e=>{const card=e.target.closest('.project');if(card&&!mobile.matches&&!reduced.matches){const i=$$('.project').indexOf(card);window.scrollTo({top:work.offsetTop+i/4*(work.offsetHeight-innerHeight),behavior:'instant'});}});
slider.addEventListener('input',()=>{scrubOverrideUntil=Date.now()+5000;if(!scrubLoaded){scrubLoaded=true;scrub.load();}seek(Number(slider.value)/100);});scrub.addEventListener('loadedmetadata',()=>seek(Number(slider.value)/100));
addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',measure);mobile.addEventListener('change',()=>{track.style.transform='';measure();});measure();
// Native dialogs provide focus containment and Escape; return focus to the opener.
const menu=$('#menu');let menuOpener=null,projectOpener=null;
$('.menu-toggle').addEventListener('click',e=>{menuOpener=e.currentTarget;menu.showModal();document.body.style.overflow='hidden';menuOpener.setAttribute('aria-expanded','true');});
function closeMenu(){menu.close();}
$('.menu-close').addEventListener('click',closeMenu);menu.addEventListener('close',()=>{document.body.style.overflow='';$('.menu-toggle').setAttribute('aria-expanded','false');menuOpener?.focus({preventScroll:true});});$$('#menu a').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id.startsWith('#')){closeMenu();return;}e.preventDefault();menuOpener=null;menu.close();document.body.style.overflow='';history.pushState(null,'',id);requestAnimationFrame(()=>$(id)?.scrollIntoView({behavior:paused?'instant':'smooth',block:'start'}));}));
const projects={
 saltlick:{title:'Saltlick',type:'Website / Food & hospitality',image:'saltlick-placeit.webp',copy:'A restaurant website with a generous serving of personality. This tablet mockup comes from the original RegMedia portfolio.',more:'Saltlick web design, shown here as an archive project.'},
 port:{title:'Port City Training and Fitness',type:'Website / Brand identity',image:'port-city.webp',copy:'Branding and a clean, functional website for Port City Training and Fitness. An ongoing creative relationship, reflected in Victoria’s testimonial below.',more:'Web design and identity, from the original RegMedia site.'},
 thb:{title:'TH&B',type:'Website / Artists & culture',image:'Screen-Shot-2019-08-01-at-4-03-10-PM.webp',copy:'A website for the creative partnership of Simon Frank, Dave Hind, Ivan Jurak and Tor Lukasik-Foss. An uncluttered stage for a group of visual artists working out of the Hamilton area.',more:'Original website screenshot from the RegMedia archive.'},
 brummel:{title:'B Brummel',type:'Website / Artists & culture',image:'b-brummel.webp',copy:'An online presence designed to make an artist’s work accessible and presentable. B Brummel describes a relationship built over nearly ten years in the original site’s testimonial.',more:'Original desktop and mobile presentation from the RegMedia portfolio.',link:'https://bbrummel.ca/',label:'Visit B Brummel'},
 niche:{title:'Niche',type:'Identity / Hair & artistry',image:'nichelogo.webp',copy:'A clear, confident typographic identity for Niche Hair and Artistry Lounge.',more:'Original identity artwork from the RegMedia portfolio.'}
};
const pd=$('#project-dialog');function openProject(data,opener){projectOpener=opener;const c=$('.project-dialog-content');c.replaceChildren();const label=document.createElement('p');label.className='eyebrow';label.textContent=data.type;const h=document.createElement('h2');h.textContent=data.title;const image=document.createElement('img');image.src='assets/'+data.image;image.alt=data.title+' — original RegMedia portfolio work';const d=document.createElement('div');d.className='project-description';const meta=document.createElement('p');meta.textContent=data.more;const body=document.createElement('div');const copy=document.createElement('p');copy.textContent=data.copy;body.append(copy);if(data.link){const a=document.createElement('a');a.className='text-link';a.href=data.link;a.target='_blank';a.rel='noopener';a.textContent=data.label+' ↗';body.append(a);}d.append(meta,body);c.append(label,h,image,d);pd.showModal();pd.scrollTop=0;document.body.style.overflow='hidden';}
$$('.project-open').forEach(b=>b.addEventListener('click',()=>openProject(projects[b.dataset.project],b)));$('.project-close').addEventListener('click',()=>pd.close());pd.addEventListener('click',e=>{if(e.target===pd){const r=pd.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)pd.close();}});pd.addEventListener('close',()=>{document.body.style.overflow='';projectOpener?.focus({preventScroll:true});});
const archive=[['Norfolk Leaf','Brand identity','norfolk-leaf-final-logo.webp'],['Mulberry Street','Website archive','mulberrystreet.webp'],['Dave Hind','Artist website','Screen-Shot-2019-08-01-at-3-44-08-PM.webp'],['Harrison Kennedy','Music website','Screen-Shot-2019-08-01-at-3-50-45-PM.webp'],['Henry Brown’s','Website archive','Screen-Shot-2019-08-01-at-3-09-47-PM.webp'],['Gorilla Cheese','Website archive','Screen-Shot-2019-08-01-at-3-29-21-PM.webp'],['Crown Point Candles','Website archive','Screen-Shot-2019-08-01-at-3-43-35-PM.webp'],['Big Proppa','Website archive','Screen-Shot-2019-08-01-at-3-52-18-PM.webp'],['Scottish Rite Club of Hamilton','Website archive','Screen-Shot-2019-08-01-at-4-16-11-PM.webp'],['Tfunk','Poster design','tfunkposter8.webp'],['Southern Smoke','Website archive','southernsmoke.webp'],['Graziano Manfredi','Photography website','Screen-Shot-2019-08-01-at-3-48-35-PM.webp']];
let archiveBuilt=false;$('#archive-toggle').addEventListener('click',()=>{const grid=$('#archive-grid'),open=grid.hidden;if(!archiveBuilt){for(const [title,type,image] of archive){const b=document.createElement('button');b.className='archive-item';const im=document.createElement('img');im.src='assets/'+image;im.alt=title+' — original portfolio artwork';im.loading='lazy';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=type+' ↗';b.append(im,h,p);b.addEventListener('click',()=>openProject({title,type,image,copy:'Selected original work from the RegMedia portfolio.',more:'Archive presentation. Project images may show an earlier version of a website.'},b));grid.append(b);}archiveBuilt=true;}grid.hidden=!open;$('#archive-toggle').setAttribute('aria-expanded',String(open));$('#archive-toggle').innerHTML=open?'Close the archive <span>−</span>':'Open the archive <span>+</span>';});
const steps=[['FIRST, A CONVERSATION.','Start with<br>a good question.','What are you trying to say? Who needs to hear it? Let’s talk about the idea, the people, and what you want to make happen.'],['FOLLOW THE POSSIBILITIES.','Give the idea<br>room to grow.','References, sketches, experiments. We explore the visual language and find the direction that feels like you.'],['TURN THE WHAT IF INTO WHAT IS.','Make it real.<br>Make it feel right.','Design meets technology. We build, refine, and check the details across screens and mediums until the experience comes together.'],['THE START OF SOMETHING ELSE.','Put it out there.<br>Keep it moving.','Launch with confidence. Keep your content current. And when the next good idea turns up, you know where to find me.']];
const tabs=$$('.process-tabs button');function step(i,focus=false){tabs.forEach((b,j)=>{b.setAttribute('aria-selected',String(i===j));b.tabIndex=i===j?0:-1;});$('#process-panel').setAttribute('aria-labelledby','step-'+i);$('#step-kicker').textContent=steps[i][0];$('#step-title').innerHTML=steps[i][1];$('#step-copy').textContent=steps[i][2];$('.step-art').dataset.step=i;$('.step-number').textContent=String(i+1).padStart(2,'0');if(!paused){$('#process-panel').animate([{opacity:.25,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],{duration:500,easing:'ease-out'});}if(focus)tabs[i].focus();}tabs.forEach((b,i)=>{b.addEventListener('click',()=>step(i));b.addEventListener('keydown',e=>{let n=i;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();step(n,true);});});
const quotes=[['Reg has always gone above and beyond, not only with making killer logos and branding but has also delivered beautiful, clean and very functional websites.','Victoria V.','Owner, Port City Training and Fitness'],['He uses elegant graphic techniques to make my work easily accessible and presentable. He continues to offer suggestions to develop the site further.','B Brummel','Artist'],['It’s easy with technology to begin to believe you can solve all your problems in house but as Reg has demonstrated to us, saving us much wasted time, you have to know how to make that tech work for you.','Todd Crocker','From the original RegMedia site']];let qi=0;function quote(dir){qi=(qi+dir+quotes.length)%quotes.length;$('#quote-text').textContent=quotes[qi][0];$('#quote-name').textContent=quotes[qi][1];$('#quote-role').textContent=quotes[qi][2];$('#quote-count').textContent='0'+(qi+1)+' / 03';if(!paused)$('#quote-text').animate([{opacity:.2},{opacity:1}],{duration:500});}$('#quote-prev').addEventListener('click',()=>quote(-1));$('#quote-next').addEventListener('click',()=>quote(1));
$('#year').textContent=new Date().getFullYear();
// Authored GPU signal field. No external animation library; idle offscreen.
const canvas=$('#field'),gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});let pointer=[.6,.5],heroVisible=true;
const heroIO=new IntersectionObserver(es=>heroVisible=es[0].isIntersecting);heroIO.observe($('.hero'));
if(gl){const vs='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';const fs=`precision highp float;
uniform vec2 resolution;uniform float time;uniform vec2 mouse;
mat2 rot(float a){return mat2(cos(a),-sin(a),sin(a),cos(a));}
float field(vec3 p){p.xz*=rot(time*.13);p.xy*=rot(.45+sin(time*.12)*.3);float angle=atan(p.y,p.x);float wave=sin(angle*4.+time*.32)*.12+sin(angle*7.-time*.18)*.035;vec2 q=vec2(length(p.xy)-1.13-wave,p.z);return length(q)-.36-sin(p.x*5.+p.y*3.+time*.4)*.045;}
vec3 normal(vec3 p){vec2 e=vec2(.003,0.);return normalize(vec3(field(p+e.xyy)-field(p-e.xyy),field(p+e.yxy)-field(p-e.yxy),field(p+e.yyx)-field(p-e.yyx)));}
void main(){vec2 uv=(gl_FragCoord.xy-.5*resolution)/resolution.y;uv.x-=resolution.x/resolution.y*.23;uv.y+=.05;uv+=vec2((mouse.x-.5)*.13,(mouse.y-.5)*.1);vec3 ro=vec3(0.,0.,4.5),rd=normalize(vec3(uv*2.5,-3.));float t=0.;float d;vec3 p;for(int i=0;i<54;i++){p=ro+rd*t;d=field(p);if(d<.004||t>8.)break;t+=d*.75;}vec3 color=vec3(.045,.046,.055);float halo=exp(-length(uv)*1.7);color+=vec3(.03,.025,.1)*halo;if(t<8.&&d<.008){vec3 n=normal(p);vec3 l=normalize(vec3(-2.,3.,4.));float diffuse=max(0.,dot(n,l));float fres=pow(1.-max(0.,dot(n,-rd)),2.);float shine=pow(max(0.,dot(reflect(-l,n),-rd)),35.);float bands=.5+.5*sin(p.y*16.+p.x*10.+time*.7+n.z*3.);vec3 tint=mix(vec3(.16,.24,.64),vec3(.72,.81,.93),smoothstep(.2,.8,bands));tint=mix(tint,vec3(.87,1.,.39),pow(max(0.,n.y),4.)*.75);color=tint*(.2+diffuse*.8)+shine*.7+fres*vec3(.18,.2,.45);color*=1.-t*.04;}color=pow(color,vec3(.9));gl_FragColor=vec4(color,1.);}`;
function compile(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
try{const prog=gl.createProgram();gl.attachShader(prog,compile(gl.VERTEX_SHADER,vs));gl.attachShader(prog,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(prog,'p');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const ures=gl.getUniformLocation(prog,'resolution'),utime=gl.getUniformLocation(prog,'time'),umouse=gl.getUniformLocation(prog,'mouse');function resizeGL(){const ratio=Math.min(devicePixelRatio,1)*(mobile.matches?.55:.8);canvas.width=Math.round(canvas.clientWidth*ratio);canvas.height=Math.round(canvas.clientHeight*ratio);gl.viewport(0,0,canvas.width,canvas.height);gl.uniform2f(ures,canvas.width,canvas.height);}resizeGL();addEventListener('resize',resizeGL);let last=0,time=0,drawn=false;function render(now){requestAnimationFrame(render);if(!heroVisible||document.hidden||now-last<40||(paused&&drawn))return;const delta=Math.min((now-last)/1000,.1);last=now;if(!paused)time+=delta;gl.uniform1f(utime,time);gl.uniform2f(umouse,pointer[0],pointer[1]);gl.drawArrays(gl.TRIANGLES,0,6);drawn=true;}requestAnimationFrame(render);}catch(e){canvas.style.display='none';console.warn('Signal field fallback:',e.message);}}
const cursor=$('.cursor');if(matchMedia('(pointer:fine)').matches){addEventListener('pointermove',e=>{pointer=[e.clientX/innerWidth,1-e.clientY/innerHeight];cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.style.opacity='1';cursor.classList.toggle('hover',!!e.target.closest('a,button,summary,input'));},{passive:true});document.addEventListener('mouseleave',()=>cursor.style.opacity='0');}
